### PR TITLE
Provide different `CursorAnimator` implementations

### PR DESCRIPTION
**Pull request by massivemadness**
I'm not sure if it's okay to put `setScale()` and `setAlpha()` methods in `SelectionHandleStyle`, but you got the idea
\+ Vibrate on long press just like normal EditText widget

_FadeCursorAnimator_
fade

_ScaleCursorAnimator_
scale

### CODE REVIEW

**Comment by massivemadness** [comment]
There's a visual issue when editing, I'm not sure how to fix this but maybe the cursor position should be updated separate from the selection handle

**Comment by Rosemoe** [comment]
> There's a visual issue when editing, I'm not sure how to fix this but maybe the cursor position should be updated separately from the selection handle

What's the issue?
Btw, thanks for your contributions!

**Comment by massivemadness** [comment]
@Rosemoe

ezgif-2-6bd2b62fa4

**Comment by massivemadness** [comment]
Yep, thanks 🤞

**Pull request merged**
